language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - pip install .
script:
  - nosetests
  - coverage run --source=kwick setup.py test
after_success:
  - coveralls
